### ISSUE TITLE
AttributeError: function 'SETPATHdll' not found

### ISSUE THREAD

**Issue by mac117** [BenThelen/python-refprop#2]
Traceback (most recent call last):
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 7377, in <module>
    _test()
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 942, in _test
    rptest.settest('refprop')
  File "C:\Users\XXX\workspace\Thermo\src\rptest.py", line 19, in settest
    _maintest(rp)
  File "C:\Users\XXX\workspace\Thermo\src\rptest.py", line 29, in _maintest
    if rp.test(): #if True; rptest =>>for testing purpose
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 981, in test
    prop = setup('def', 'air')
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 1492, in setup
    _load()
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 417, in _load
    setpath()
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 512, in setpath
    _setpath(path)
  File "C:\Users\XXX\workspace\Thermo\src\refprop.py", line 552, in _setpath
    _rp.SETPATHdll(ctypes.byref(_hpth), ctypes.c_long(255))
  File "C:\Python33-32bit\lib\ctypes__init__.py", line 366, in **getattr**
    func = self.**getitem**(name)
  File "C:\Python33-32bit\lib\ctypes__init__.py", line 371, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SETPATHdll' not found

Any idea?

**Comment by BenThelen** [comment]
Python-refprop is a wrapper for NIST database 23 (aka refprop), this needs to be installed on your system, or this is installed but in an different directory. Either install refprop in c:/program files/refprop/ or c:/program files (x86)/refprop/ or change line 501 from refprop.py
